 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task_trackers", type: :request do
  # TaskTracker. As you add validations to TaskTracker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaskTracker.create! valid_attributes
      get task_trackers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task_tracker = TaskTracker.create! valid_attributes
      get task_tracker_url(task_tracker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_tracker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      task_tracker = TaskTracker.create! valid_attributes
      get edit_task_tracker_url(task_tracker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaskTracker" do
        expect {
          post task_trackers_url, params: { task_tracker: valid_attributes }
        }.to change(TaskTracker, :count).by(1)
      end

      it "redirects to the created task_tracker" do
        post task_trackers_url, params: { task_tracker: valid_attributes }
        expect(response).to redirect_to(task_tracker_url(TaskTracker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaskTracker" do
        expect {
          post task_trackers_url, params: { task_tracker: invalid_attributes }
        }.to change(TaskTracker, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post task_trackers_url, params: { task_tracker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_tracker" do
        task_tracker = TaskTracker.create! valid_attributes
        patch task_tracker_url(task_tracker), params: { task_tracker: new_attributes }
        task_tracker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task_tracker" do
        task_tracker = TaskTracker.create! valid_attributes
        patch task_tracker_url(task_tracker), params: { task_tracker: new_attributes }
        task_tracker.reload
        expect(response).to redirect_to(task_tracker_url(task_tracker))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        task_tracker = TaskTracker.create! valid_attributes
        patch task_tracker_url(task_tracker), params: { task_tracker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task_tracker" do
      task_tracker = TaskTracker.create! valid_attributes
      expect {
        delete task_tracker_url(task_tracker)
      }.to change(TaskTracker, :count).by(-1)
    end

    it "redirects to the task_trackers list" do
      task_tracker = TaskTracker.create! valid_attributes
      delete task_tracker_url(task_tracker)
      expect(response).to redirect_to(task_trackers_url)
    end
  end
end
