SustainableDevelopmentGoal.create(name: "Affordable and Clean Energy", long_title: "Ensure access to affordable, reliable, sustainable and modern energy for all", slug: 'affordable_and_clean_energy', number: 7) if SustainableDevelopmentGoal.where(slug: 'affordable_and_clean_energy').empty?
SustainableDevelopmentGoal.create(name: "Clean Water and Sanitation", long_title: "Ensure availability and sustainable management of water and sanitation for all", slug: 'clean_water_and_sanitation', number: 6) if SustainableDevelopmentGoal.where(slug: 'clean_water_and_sanitation').empty?
SustainableDevelopmentGoal.create(name: "Climate Action", long_title: "Take urgent action to combat climate change and its impacts", slug: 'climate_action', number: 13) if SustainableDevelopmentGoal.where(slug: 'climate_action').empty?
SustainableDevelopmentGoal.create(name: "Decent Work and Economic Growth", long_title: "Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all", slug: 'decent_work_and_economic_growth', number: 8) if SustainableDevelopmentGoal.where(slug: 'decent_work_and_economic_growth').empty?
SustainableDevelopmentGoal.create(name: "Gender Equality", long_title: "Achieve gender equality and empower all women and girls", slug: 'gender_equality', number: 5) if SustainableDevelopmentGoal.where(slug: 'gender_equality').empty?
SustainableDevelopmentGoal.create(name: "Good Health and Well-Being", long_title: "Ensure healthy lives and promote well-being for all at all ages", slug: 'good_health_and_wellbeing', number: 3) if SustainableDevelopmentGoal.where(slug: 'good_health_and_wellbeing').empty?
SustainableDevelopmentGoal.create(name: "Industry, Innovation and Infrastructure", long_title: "Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation", slug: 'industry_innovation_and_infrastr', number: 9) if SustainableDevelopmentGoal.where(slug: 'industry_innovation_and_infrastr').empty?
SustainableDevelopmentGoal.create(name: "Life Below Water", long_title: "Conserve and sustainably use the oceans, seas and marine resources for sustainable development", slug: 'life_below_water', number: 14) if SustainableDevelopmentGoal.where(slug: 'life_below_water').empty?
SustainableDevelopmentGoal.create(name: "Life on Land", long_title: "Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss", slug: 'life_on_land', number: 15) if SustainableDevelopmentGoal.where(slug: 'life_on_land').empty?
SustainableDevelopmentGoal.create(name: "No Poverty", long_title: "End poverty in all its forms everywhere", slug: 'no_poverty', number: 1) if SustainableDevelopmentGoal.where(slug: 'no_poverty').empty?
SustainableDevelopmentGoal.create(name: "Partnerships for the Goals", long_title: "Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development", slug: 'partnerships_for_the_goals', number: 17) if SustainableDevelopmentGoal.where(slug: 'partnerships_for_the_goals').empty?
SustainableDevelopmentGoal.create(name: "Peace, Justice and Strong Institutions", long_title: "Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels", slug: 'peace_justice_and_strong_institu', number: 16) if SustainableDevelopmentGoal.where(slug: 'peace_justice_and_strong_institu').empty?
SustainableDevelopmentGoal.create(name: "Quality Education", long_title: "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all", slug: 'quality_education', number: 4) if SustainableDevelopmentGoal.where(slug: 'quality_education').empty?
SustainableDevelopmentGoal.create(name: "Reduced Inequalities", long_title: "Reduce inequality within and among countries", slug: 'reduced_inequalities', number: 10) if SustainableDevelopmentGoal.where(slug: 'reduced_inequalities').empty?
SustainableDevelopmentGoal.create(name: "Responsible Consumption and Production", long_title: "Ensure sustainable consumption and production patterns", slug: 'responsible_consumption_and_prod', number: 12) if SustainableDevelopmentGoal.where(slug: 'responsible_consumption_and_prod').empty?
SustainableDevelopmentGoal.create(name: "Sustainable Cities and Communities", long_title: "Make cities and human settlements inclusive, safe, resilient and sustainable", slug: 'sustainable_cities_and_communiti', number: 11) if SustainableDevelopmentGoal.where(slug: 'sustainable_cities_and_communiti').empty?
SustainableDevelopmentGoal.create(name: "Zero Hunger", long_title: "End hunger, achieve food security and improved nutrition and promote sustainable agriculture", slug: 'zero_hunger', number: 2) if SustainableDevelopmentGoal.where(slug: 'zero_hunger').empty?
