sips -s format png abt_associates.jpg --out abt_associates.png
sips -s format png awaazde.jpg --out awaazde.png
sips -s format png belgian_development_agency.jpg --out belgian_development_agency.png
sips -s format png caktus_group.jpg --out caktus_group.png
sips -s format png catholic_relief_services_crs.jpg --out catholic_relief_services_crs.png
sips -s format png center_for_international_private.jpg --out center_for_international_private.png
sips -s format png charlie_goldsmith_associates.jpg --out charlie_goldsmith_associates.png
sips -s format png code_innovation.jpg --out code_innovation.png
sips -s format png creative_associates_internationa.jpg --out creative_associates_internationa.png
sips -s format png digital_impact_alliance_dial.jpg --out digital_impact_alliance_dial.png
sips -s format png el_kanis_group.jpg --out el_kanis_group.png
sips -s format png enabel.jpg --out enabel.png
sips -s format png fhi_.jpg --out fhi_.png
sips -s format png foundation_botnar.jpg --out foundation_botnar.png
sips -s format png girl_effect_mobile__springster.jpg --out girl_effect_mobile__springster.png
sips -s format png giz.jpg --out giz.png
sips -s format png good_business.jpg --out good_business.png
sips -s format png institute_of_development_studies.jpg --out institute_of_development_studies.png
sips -s format png interamerican_development_bank_i.jpg --out interamerican_development_bank_i.png
sips -s format png international_foundation_for_ele.jpg --out international_foundation_for_ele.png
sips -s format png international_rescue_committee_i.jpg --out international_rescue_committee_i.png
sips -s format png internews.jpg --out internews.png
sips -s format png intrahealth_international.jpg --out intrahealth_international.png
sips -s format png irex.jpg --out irex.png
sips -s format png jhpiego.jpg --out jhpiego.png
sips -s format png john_snow_inc_jsi.jpg --out john_snow_inc_jsi.png
sips -s format png kimetrica.jpg --out kimetrica.png
sips -s format png living_goods.jpg --out living_goods.png
sips -s format png louis_berger.jpg --out louis_berger.png
sips -s format png lutheran_world_relief.jpg --out lutheran_world_relief.png
sips -s format png nafundi.jpg --out nafundi.png
sips -s format png national_democratic_institute_nd.jpg --out national_democratic_institute_nd.png
sips -s format png norwegian_peoples_aid.jpg --out norwegian_peoples_aid.png
sips -s format png openhie.jpg --out openhie.png
sips -s format png palladium.jpg --out palladium.png
sips -s format png path.jpg --out path.png
sips -s format png public_administration_internatio.jpg --out public_administration_internatio.png
sips -s format png reboot.jpg --out reboot.png
sips -s format png resolve_to_save_lives.jpg --out resolve_to_save_lives.png
sips -s format png rti_international.jpg --out rti_international.png
sips -s format png smart_resultancy.jpg --out smart_resultancy.png
sips -s format png souktel.jpg --out souktel.png
sips -s format png swedish_international_developmen.jpg --out swedish_international_developmen.png
sips -s format png terre_des_hommes.jpg --out terre_des_hommes.png
sips -s format png the_food_and_agriculture_organiz.jpg --out the_food_and_agriculture_organiz.png
sips -s format png thinkmd.jpg --out thinkmd.png
sips -s format png tropical_health_and_education_tr.jpg --out tropical_health_and_education_tr.png
sips -s format png united_nations_environment_progr.jpg --out united_nations_environment_progr.png
sips -s format png united_nations_interregional_cri.jpg --out united_nations_interregional_cri.png
sips -s format png villagereach.jpg --out villagereach.png
sips -s format png welthungerhilfe.jpg --out welthungerhilfe.png
sips -s format png world_agroforestry_center_icraf.jpg --out world_agroforestry_center_icraf.png
